// custom properties
:url-repo: https://github.com/bettercodepaul/programming-challenge

= BettercallPaul programming challenge

== Tasks

Weather::
    In `weather.csv` you'll find the daily weather data of a single month.
    Read the file, then output the day number (column one `Day`) of the day with
    the smallest temperature spread (difference between maximum &
    minimum temperature of the day.)
    The maximum temperature is the second column `MxT`, the minimum
    temperature the third column `MnT`.

Countries::
    `countries.csv` contains a list of data about the 27 countries of the European
    Union.
    Use the columns `Population` and `Area` to compute each country's population
    density. Read the file, then print the name of the country with the highest number
    of people per square kilometre.

Task::
    1. Write a single program which is able to solve the "Weather" challenge.
    2. Then refactor and extend your solution such that it additionally
       supports the Countries challenge.

== Building and running

After installing Maven 3.x or by calling the included Maven wrapper (`mvnw` and `mvnw.cmd`, depending on your operating system) you should be able to

Build & test your project::
    `mvn verify`

Then to run the main class _de.bcxp.challenge.App_::
    `mvn exec:java`

To remove the compilation output::
    `mvn clean`

Or use your IDE functionality::
    to run & debug your program.

== Time estimation
~2h getting accustomed to and setting up Java
~2h planning for the challenge
~?h implementing, debugging and testing

== AI use disclaimer

AI was used during the research and planning phase for creating feedback.
All code is entirely handwritten.