name: Run java tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: '27'
          distribution: 'temurin'
      - name: Run maven verify
        run: mvn verify